name: Docker
on:
  push:
    branches:
      - master
    paths:
      - pillar/**
      - salt/**
      - docker/**
      - .github/workflows/docker.yml

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/agent:1.0
            ${{ github.repository_owner }}/agent:latest
